<a href="https://colab.research.google.com/github/Justo-sys/Web_Scraping/blob/main/Web_Scraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Web Scraping Project

This project demonstrates web scraping using Python to collect structured data from a live website using Requests, BeautifulSoup, and Pandas

### Importing libraries

In [35]:
#Importing libraries that I will need for webscraping
from bs4 import BeautifulSoup
import requests
import pandas as pd

### Getting the webpage

In [36]:
#set URL of website in a variable
url = 'https://www.scrapethissite.com/pages/forms/'
page = requests.get(url)

# Check if request was successful
page.status_code

200

Parsing the HTML

In [37]:
#Use BeautifulSoup to extract the HTML content
soup = BeautifulSoup(page.text, 'html.parser')
print(soup)

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="hockey">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Hockey Teams: Forms, Searching and Pagination
                            <small>25 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">http://www.opensourcesports.com/hockey/</a>
</p>
<hr/>
</div>
</div>
<div class="row search-area">
<div class="col-md-12 text-center">
<form action="/pages/forms/" class="form form-inline" method="GET">
<label for="q">
                                Search for Teams:
                            </label>
<input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
<input class="btn btn-primary" type="submit" value="Search"/>
</form>
<hr/>
</div>
</div><!--.row.search-area-->
<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            44
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.55
                        </td>
<td class="gf">
                            299
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            292
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-success">
                            14
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            344
                        </td>
<td class="ga">
                            263
                        </td>
<td class="diff text-success">
                            81
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            49
                        </td>
<td class="losses">
                            23
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.613
                        </td>
<td class="gf">
                            284
                        </td>
<td class="ga">
                            211
                        </td>
<td class="diff text-success">
                            73
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.425
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            298
                        </td>
<td class="diff text-danger">
                            -25
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            272
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            238
                        </td>
<td class="ga">
                            276
                        </td>
<td class="diff text-danger">
                            -38
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            340
                        </td>
<td class="ga">
                            254
                        </td>
<td class="diff text-success">
                            86
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Minnesota North Stars
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            27
                        </td>
<td class="losses">
                            39
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.338
                        </td>
<td class="gf">
                            256
                        </td>
<td class="ga">
                            266
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.487
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            249
                        </td>
<td class="diff text-success">
                            24
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            8
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            25
                        </td>
<td class="losses">
                            45
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.312
                        </td>
<td class="gf">
                            223
                        </td>
<td class="ga">
                            290
                        </td>
<td class="diff text-danger">
                            -67
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            297
                        </td>
<td class="ga">
                            265
                        </td>
<td class="diff text-success">
                            32
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            33
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.412
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            267
                        </td>
<td class="diff text-danger">
                            -15
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.512
                        </td>
<td class="gf">
                            342
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-success">
                            37
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Quebec Nordiques
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            16
                        </td>
<td class="losses">
                            50
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.2
                        </td>
<td class="gf">
                            236
                        </td>
<td class="ga">
                            354
                        </td>
<td class="diff text-danger">
                            -118
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            47
                        </td>
<td class="losses">
                            22
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.588
                        </td>
<td class="gf">
                            310
                        </td>
<td class="ga">
                            250
                        </td>
<td class="diff text-success">
                            60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            23
                        </td>
<td class="losses">
                            46
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.287
                        </td>
<td class="gf">
                            241
                        </td>
<td class="ga">
                            318
                        </td>
<td class="diff text-danger">
                            -77
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            28
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.35
                        </td>
<td class="gf">
                            243
                        </td>
<td class="ga">
                            315
                        </td>
<td class="diff text-danger">
                            -72
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            258
                        </td>
<td class="ga">
                            258
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">

### Finding the table

In [38]:
#Extract the table with the Hockey Scores
hockey_table = soup.find('table', class_='table')
print(hockey_table)

<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            44
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.55
                        </td>
<td class="gf">
                            299
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            292
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-success">
                            14
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            344
                        </td>
<td class="ga">
                            263
                        </td>
<td class="diff text-success">
                            81
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            49
                        </td>
<td class="losses">
                            23
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.613
                        </td>
<td class="gf">
                            284
                        </td>
<td class="ga">
                            211
                        </td>
<td class="diff text-success">
                            73
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.425
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            298
                        </td>
<td class="diff text-danger">
                            -25
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            272
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            238
                        </td>
<td class="ga">
                            276
                        </td>
<td class="diff text-danger">
                            -38
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            340
                        </td>
<td class="ga">
                            254
                        </td>
<td class="diff text-success">
                            86
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Minnesota North Stars
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            27
                        </td>
<td class="losses">
                            39
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.338
                        </td>
<td class="gf">
                            256
                        </td>
<td class="ga">
                            266
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.487
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            249
                        </td>
<td class="diff text-success">
                            24
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            8
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            25
                        </td>
<td class="losses">
                            45
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.312
                        </td>
<td class="gf">
                            223
                        </td>
<td class="ga">
                            290
                        </td>
<td class="diff text-danger">
                            -67
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            297
                        </td>
<td class="ga">
                            265
                        </td>
<td class="diff text-success">
                            32
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            33
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.412
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            267
                        </td>
<td class="diff text-danger">
                            -15
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.512
                        </td>
<td class="gf">
                            342
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-success">
                            37
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Quebec Nordiques
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            16
                        </td>
<td class="losses">
                            50
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.2
                        </td>
<td class="gf">
                            236
                        </td>
<td class="ga">
                            354
                        </td>
<td class="diff text-danger">
                            -118
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            47
                        </td>
<td class="losses">
                            22
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.588
                        </td>
<td class="gf">
                            310
                        </td>
<td class="ga">
                            250
                        </td>
<td class="diff text-success">
                            60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            23
                        </td>
<td class="losses">
                            46
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.287
                        </td>
<td class="gf">
                            241
                        </td>
<td class="ga">
                            318
                        </td>
<td class="diff text-danger">
                            -77
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            28
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.35
                        </td>
<td class="gf">
                            243
                        </td>
<td class="ga">
                            315
                        </td>
<td class="diff text-danger">
                            -72
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            258
                        </td>
<td class="ga">
                            258
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            26
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.325
                        </td>
<td class="gf">
                            260
                        </td>
<td class="ga">
                            288
                        </td>
<td class="diff text-danger">
                            -28
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            32
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            270
                        </td>
<td class="ga">
                            275
                        </td>
<td class="diff text-danger">
                            -5
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            289
                        </td>
<td class="ga">
                            299
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            296
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-danger">
                            -9
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            29
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            257
                        </td>
<td class="ga">
                            236
                        </td>
<td class="diff text-success">
                            21
                        </td>
</tr>
</table>

### Extracting column names

In [39]:
#Extract the column headings
table_titles = hockey_table.find_all('th')
hockey_table_title = [title.text.strip() for title in table_titles]
print(hockey_table_title)

['Team Name', 'Year', 'Wins', 'Losses', 'OT Losses', 'Win %', 'Goals For (GF)', 'Goals Against (GA)', '+ / -']

### Creating an empty DataFrame

In [40]:
#Save the column headings onto a Pandas DataFrame
df = pd.DataFrame(columns=hockey_table_title)
df

Empty DataFrame
Columns: [Team Name, Year, Wins, Losses, OT Losses, Win %, Goals For (GF), Goals Against (GA), + / -]
Index: []

### Extracting row data and adding them to the DataFrame

In [45]:
#Extract the data row by row. First get all rows, then loop through each while stripping and saving data into the DataFrame
table_data = hockey_table.find_all('tr')
for row in table_data[1:]:
  raw_data = row.find_all('td')
  each_raw_data = [data.text.strip() for data in raw_data]
  print(each_raw_data)
  #saving each row data as it is generated into the pandas data frame
  length = len(df)
  df.loc[length] = each_raw_data

['Boston Bruins', '1990', '44', '24', '', '0.55', '299', '264', '35']
['Buffalo Sabres', '1990', '31', '30', '', '0.388', '292', '278', '14']
['Calgary Flames', '1990', '46', '26', '', '0.575', '344', '263', '81']
['Chicago Blackhawks', '1990', '49', '23', '', '0.613', '284', '211', '73']
['Detroit Red Wings', '1990', '34', '38', '', '0.425', '273', '298', '-25']
['Edmonton Oilers', '1990', '37', '37', '', '0.463', '272', '272', '0']
['Hartford Whalers', '1990', '31', '38', '', '0.388', '238', '276', '-38']
['Los Angeles Kings', '1990', '46', '24', '', '0.575', '340', '254', '86']
['Minnesota North Stars', '1990', '27', '39', '', '0.338', '256', '266', '-10']
['Montreal Canadiens', '1990', '39', '30', '', '0.487', '273', '249', '24']
['New Jersey Devils', '1990', '32', '33', '', '0.4', '272', '264', '8']
['New York Islanders', '1990', '25', '45', '', '0.312', '223', '290', '-67']
['New York Rangers', '1990', '36', '31', '', '0.45', '297', '265', '32']
['Philadelphia Flyers', '1990', '33', '37', '', '0.412', '252', '267', '-15']
['Pittsburgh Penguins', '1990', '41', '33', '', '0.512', '342', '305', '37']
['Quebec Nordiques', '1990', '16', '50', '', '0.2', '236', '354', '-118']
['St. Louis Blues', '1990', '47', '22', '', '0.588', '310', '250', '60']
['Toronto Maple Leafs', '1990', '23', '46', '', '0.287', '241', '318', '-77']
['Vancouver Canucks', '1990', '28', '43', '', '0.35', '243', '315', '-72']
['Washington Capitals', '1990', '37', '36', '', '0.463', '258', '258', '0']
['Winnipeg Jets', '1990', '26', '43', '', '0.325', '260', '288', '-28']
['Boston Bruins', '1991', '36', '32', '', '0.45', '270', '275', '-5']
['Buffalo Sabres', '1991', '31', '37', '', '0.388', '289', '299', '-10']
['Calgary Flames', '1991', '31', '37', '', '0.388', '296', '305', '-9']
['Chicago Blackhawks', '1991', '36', '29', '', '0.45', '257', '236', '21']

### Viewing the DataFrame

In [46]:
#Inspect the resulting DataFrame
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Chicago Blackhawks,1991,36,29,,0.45,257,236,21
1,Boston Bruins,1990,44,24,,0.55,299,264,35
2,Buffalo Sabres,1990,31,30,,0.388,292,278,14
3,Calgary Flames,1990,46,26,,0.575,344,263,81
4,Chicago Blackhawks,1990,49,23,,0.613,284,211,73
5,Detroit Red Wings,1990,34,38,,0.425,273,298,-25
6,Edmonton Oilers,1990,37,37,,0.463,272,272,0
7,Hartford Whalers,1990,31,38,,0.388,238,276,-38
8,Los Angeles Kings,1990,46,24,,0.575,340,254,86
9,Minnesota North Stars,1990,27,39,,0.338,256,266,-10
10,Montreal Canadiens,1990,39,30,,0.487,273,249,24
11,New Jersey Devils,1990,32,33,,0.4,272,264,8
12,New York Islanders,1990,25,45,,0.312,223,290,-67
13,New York Rangers,1990,36,31,,0.45,297,265,32
14,Philadelphia Flyers,1990,33,37,,0.412,252,267,-15
15,Pittsburgh Penguins,1990,41,33,,0.512,342,305,37
16,Quebec Nordiques,1990,16,50,,0.2,236,354,-118
17,St. Louis Blues,1990,47,22,,0.588,310,250,60
18,Toronto Maple Leafs,1990,23,46,,0.287,241,318,-77
19,Vancouver Canucks,1990,28,43,,0.35,243,315,-72
20,Washington Capitals,1990,37,36,,0.463,258,258,0
21,Winnipeg Jets,1990,26,43,,0.325,260,288,-28
22,Boston Bruins,1991,36,32,,0.45,270,275,-5
23,Buffalo Sabres,1991,31,37,,0.388,289,299,-10
24,Calgary Flames,1991,31,37,,0.388,296,305,-9
25,Chicago Blackhawks,1991,36,29,,0.45,257,236,21

### Saving to CSV

In [47]:
#Save to a .csv file in the current folder
df.to_csv(r'./Hockey.csv')